export const FETCH_ARTICLES_REQUESTS = 'FETCH_ARTICLES_REQUESTS';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const FETCH_ARTICLES_BY_ID_REQUESTS = 'FETCH_ARTICLES_BY_ID_REQUESTS';
export const FETCH_ARTICLES_BY_ID_SUCCESS = 'FETCH_ARTICLES_BY_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ID_ERROR = 'FETCH_ARTICLES_BY_ID_ERROR';